### ISSUE TITLE
Better way to specify LIMIT in the SQL SELECT

### ISSUE THREAD

**Issue by mudrd8mz** [lexxkoto/local_backupcleaner#2]
https://github.com/lexxkoto/local_backupcleaner/blob/bc592137505022e4112713d423c5904a6f298a8d/classes/task/deletebackups.php#L44

Hard-coding the `LIMIT` like this is discouraged for cross-db compatibility reasons.

Please see the method signature - https://docs.moodle.org/dev/Data_manipulation_API#get_records_sql

**Comment by mudrd8mz** [comment]
On that note, please also refer to https://docs.moodle.org/dev/Data_manipulation_API#Placeholders

**Comment by lexxkoto** [comment]
Changed the query to use a parameter array and moved the LIMIT out of the raw sql.
