### ISSUE TITLE
Better selection of what to delete

### ISSUE THREAD

**Issue by mudrd8mz** [lexxkoto/local_backupcleaner#3]
https://github.com/lexxkoto/local_backupcleaner/blob/bc592137505022e4112713d423c5904a6f298a8d/classes/task/deletebackups.php#L42

So this seems to delete any old MBZ file it finds, regardless of where it is saved. So if someone has an archive stored in their private files, it would delete it, too. If there was a Folder activity resources in a course with some MBZ files (e.g. templates in a Library like course for new semester courses), it would delete them, too.

Would it be better to limit the search to only the actual backup file areas?

**Comment by lexxkoto** [comment]
In the long term I'll probably add more configuration options that users can turn on and off via the settings page, but in the meantime would adding this to the WHERE clause be sufficient in your eyes?

`(component="backup" OR component="user")`

**Comment by lexxkoto** [comment]
Added component check to query.

**Comment by danmarsden** [comment]
fyi - our allbackup report might also give you some tips (excluding recyclebin is also a good plan)
https://github.com/catalyst/moodle-report_allbackups

https://github.com/catalyst/moodle-report_allbackups/blob/MOODLE_400_STABLE/index.php#L256

I've also thought the functionality you're working on here would sit quite nicely as a feature in our allbackups report plugin but never got round to adding it - (our plugin doesn't just support backups in the files table, but also the scheduled backups stored in a specific directory by the scheduled backups settings.)
